#ifndef CHARM_CI_CHARMCOMMANDPROTOCOL_H
#define CHARM_CI_CHARMCOMMANDPROTOCOL_H

#define CHARM_CI_VERSION                    0x0001

#define CHARM_CI_COMMAND_DISCONNECT         "BYE"
#define CHARM_CI_COMMAND_RECENT             "RECENT"
#define CHARM_CI_COMMAND_START              "START"
#define CHARM_CI_COMMAND_STATUS             "STATUS"
#define CHARM_CI_COMMAND_STOP               "STOP"
#define CHARM_CI_COMMAND_TASK               "TASK"
#define CHARM_CI_EVENT_TASK_ACTIVATED       "TASK ACTIVATED"
#define CHARM_CI_EVENT_TASK_ADDED           "TASK ADDED"
#define CHARM_CI_EVENT_TASK_DEACTIVATED     "TASK DEACTIVATED"
#define CHARM_CI_EVENT_TASK_MODIFIED        "TASK MODIFIED"
#define CHARM_CI_EVENT_TASK_RESET           "TASK RESET"
#define CHARM_CI_HANDSHAKE_RECV             "READY"
#define CHARM_CI_HANDSHAKE_SEND             "HELLO CI"
#define CHARM_CI_SERVER_ACK                 "ACK"
#define CHARM_CI_SERVER_COMMENT             "*"
#define CHARM_CI_SERVER_NAK                 "NAK"

#endif // CHARM_CI_CHARMCOMMANDPROTOCOL_H

